name: CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:


jobs:
  python_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-python@v2  
      - run: pip install -r requirements.txt
      - run: python -m pip install --upgrade pip
      - run: python --version

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-python@v2  
      - run: pip install -r requirements.txt
      - run: python -m pip install --upgrade pip
      - run: pip install pylint
      - run: pip install flask
      - run: pylint **/*.py